#!/bin/bash

MAX=${1:-12}
NOW_UTC=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

XSL=$(dirname $0)/rfc-atom.xsl

curl --silent --show-error "http://www.rfc-editor.org/in-notes/rfc-index.xml" \
    | xsltproc --stringparam now "$NOW_UTC" --stringparam max "$MAX" "$XSL" -
